{
    'name': 'DRKDS Greenhouse Management Base',
    'version': '17.0.1.0.0',
    'category': 'Manufacturing',
    'summary': 'Base module for greenhouse component management',
    'author': 'DRKDS',
    'depends': ['base', 'mail', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/pipe_type_data.xml',
        'data/pipe_size_data.xml',
        'data/pipe_wall_thickness_data.xml',
        'data/length_master_data.xml',
        'wizard/bulk_pipe_wizard_views.xml',
        'views/greenhouse_project_views.xml',
        'views/component_line_views.xml',
        'views/pipe_management_views.xml',
        'views/length_master_views.xml',
        'views/menu_views.xml',
        'report/greenhouse_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}